version: '3'
services:
    mysql:
      image: mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      volumes:
          - "./db:/docker-entrypoint-initdb.d"
          - "./mysql:/etc/mysql/conf.d"
      ports:
          - "3306:3306"
    php-fpm:
        build:
            context: "."
            dockerfile: "php-fpm/Dockerfile"
        volumes:
            - "./www:/var/www/html"
        depends_on:
            - "mysql"
        environment:
            DATABASE_HOST: mysql
    nginx:
        image: "nginx:alpine"
        volumes:
            - "./www:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        depends_on:
            - "php-fpm"
